import { StyleSheet } from 'react-native';

import {
  DISPLAY_FONT,
  DISPLAY_FONT_MEDIUM,
  MONO_FONT,
  SANS_FONT,
  SANS_FONT_SEMIBOLD,
  type WalletColors,
} from '@components/ui/walletDesign';

export const createHomeStyles = (colors: WalletColors) => StyleSheet.create({
  shell: { flex: 1, paddingHorizontal: 12, paddingTop: 12, paddingBottom: 0 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', position: 'relative' },
  headerTitleWrap: { position: 'absolute', left: 56, right: 56, alignItems: 'center' },
  headerTitle: { color: colors.text, fontFamily: DISPLAY_FONT_MEDIUM, fontSize: 17, letterSpacing: -0.2 },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  walletBar: { alignItems: 'center', marginTop: 10 },
  walletPill: {
    minHeight: 34,
    maxWidth: '100%',
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  walletDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.signal },
  walletName: { color: colors.text, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 13 },
  walletAddress: { color: colors.textSoft, fontFamily: MONO_FONT, fontSize: 11, flexShrink: 1 },
  walletCopy: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  balanceBlock: { alignItems: 'center', marginTop: 16, marginBottom: 14 },
  balanceLabel: {
    color: '#62BBFF',
    fontFamily: MONO_FONT,
    fontSize: 10,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  balanceRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 6 },
  balanceValue: { color: colors.text, fontFamily: DISPLAY_FONT, fontSize: 52, lineHeight: 56, letterSpacing: -2.4 },
  balanceUnit: { color: colors.textSoft, fontFamily: DISPLAY_FONT_MEDIUM, fontSize: 28, marginBottom: 7 },
  balanceDelta: { minHeight: 30, marginTop: 10, paddingHorizontal: 12 },
  balanceDeltaNeutral: { backgroundColor: colors.surfaceSoft, borderColor: colors.borderStrong },
  balanceDeltaPositive: { backgroundColor: colors.successSoft, borderColor: 'rgba(52, 211, 153, 0.35)' },
  balanceDeltaNegative: { backgroundColor: colors.dangerSoft, borderColor: 'rgba(255, 122, 122, 0.35)' },
  balanceDeltaText: { color: colors.text, fontFamily: MONO_FONT, fontSize: 11 },
  quickActions: { flexDirection: 'row', gap: 9, marginBottom: 14 },
  quickAction: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  quickActionPrimary: { borderColor: colors.signalBorder, backgroundColor: colors.signalSoft },
  quickIcon: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center' },
  quickLabel: { color: colors.textMuted, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 12 },
  quickLabelPrimary: { color: colors.text },
  tabsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingBottom: 10,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tabItem: { gap: 8 },
  tabText: { color: colors.textSoft, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 14 },
  tabTextActive: { color: colors.text },
  tabIndicator: { height: 3, borderRadius: 999, backgroundColor: colors.signal },
  tabsSpacer: { flex: 1 },
  tabIconButton: { width: 30, height: 30, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  tabIconButtonBusy: { opacity: 0.45 },
  listWrap: { flex: 1, minHeight: 0 },
  listScroll: { flex: 1 },
  listScrollContent: { paddingBottom: 0 },
  listCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  assetRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 12, paddingVertical: 13 },
  assetTapArea: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  coinBadge: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  coinBadgeSoft: { backgroundColor: colors.surfaceSoft, borderColor: colors.border },
  coinBadgeText: { color: '#F8FBFF', fontFamily: DISPLAY_FONT, fontSize: 14, letterSpacing: -0.4 },
  coinBadgeLogo: { width: 26, height: 26, borderRadius: 999 },
  assetInfo: { flex: 1 },
  assetTopLine: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  assetSymbol: { color: colors.text, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 15 },
  assetTag: {
    color: colors.textSoft,
    fontFamily: MONO_FONT,
    fontSize: 10,
    backgroundColor: colors.surfaceSoft,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  assetBottomLine: { color: colors.textSoft, fontFamily: SANS_FONT, fontSize: 12, marginTop: 4 },
  assetRight: { alignItems: 'flex-end', gap: 4 },
  assetBalance: { color: colors.text, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 14 },
  assetQuote: { color: colors.textSoft, fontFamily: MONO_FONT, fontSize: 12 },
  assetIconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetDivider: { height: 1, backgroundColor: '#203149', marginHorizontal: 16 },
  manageRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 12, paddingVertical: 14 },
  emptyState: { alignItems: 'center', paddingHorizontal: 22, paddingVertical: 28 },
  emptyIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: { color: colors.text, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 15, marginTop: 14 },
  emptyBody: {
    color: colors.textSoft,
    fontFamily: SANS_FONT,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 6,
  },
  activityRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 12, paddingVertical: 13 },
  activityIconWrap: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  activityIconSend: { backgroundColor: colors.dangerSoft },
  activityIconReceive: { backgroundColor: colors.successSoft },
  activityInfo: { flex: 1 },
  activityTitle: { color: colors.text, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 14 },
  activitySubtitle: { color: colors.textSoft, fontFamily: SANS_FONT, fontSize: 12, marginTop: 4 },
  activityRight: { alignItems: 'flex-end', gap: 4 },
  activityAmount: { color: colors.text, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 13 },
  activityTime: { color: colors.textSoft, fontFamily: MONO_FONT, fontSize: 10 },
  bottomDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 12,
    paddingHorizontal: 8,
    paddingTop: 10,
    backgroundColor: 'rgba(5, 7, 13, 0.92)',
  },
  bottomDockInner: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    paddingVertical: 7,
    paddingHorizontal: 6,
  },
  bottomItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 },
  bottomCenter: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 },
  bottomCenterBubble: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.signal,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -16,
  },
  bottomLabel: { color: colors.textSoft, fontFamily: SANS_FONT_SEMIBOLD, fontSize: 10 },
  bottomLabelActive: { color: colors.text },
  bottomCenterLabel: { color: '#8FD1FF' },
});
