import { StyleSheet } from 'react-native';

import {
  DISPLAY_FONT,
  MONO_FONT,
  SANS_FONT,
  SANS_FONT_SEMIBOLD,
  WALLET_COLORS,
  buildWalletScreenStyles,
  type WalletColors,
} from '@components/ui/walletDesign';

export const createReceiveScreenBase = (colors: WalletColors) =>
  buildWalletScreenStyles(colors);

export const styles = StyleSheet.create({
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiveScroll: {
    paddingVertical: 16,
    gap: 18,
  },
  chipRow: {
    gap: 10,
    paddingTop: 12,
    paddingBottom: 10,
    alignItems: 'center',
  },
  filterChip: {
    minWidth: 52,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  filterChipOn: {
    borderColor: WALLET_COLORS.signalBorder,
    backgroundColor: WALLET_COLORS.signalSoft,
  },
  warningCard: {
    padding: 14,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  warningIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: WALLET_COLORS.signalSoft,
  },
  warningText: {
    flex: 1,
    color: WALLET_COLORS.textMuted,
    fontFamily: SANS_FONT,
    fontSize: 12.5,
    lineHeight: 18,
  },
  receiveCoinHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  receiveCoinText: {
    color: WALLET_COLORS.text,
    fontFamily: DISPLAY_FONT,
    fontSize: 24,
  },
  receiveBadge: {
    minHeight: 28,
    paddingHorizontal: 10,
    backgroundColor: WALLET_COLORS.surfaceSoft,
  },
  receiveBadgeText: {
    color: WALLET_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 11,
  },
  qrCard: {
    padding: 18,
    alignItems: 'center',
    gap: 16,
  },
  qrMock: {
    width: 238,
    height: 238,
    borderRadius: 22,
    backgroundColor: '#F2F5FA',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  qrCornerTL: {
    display: 'none',
    position: 'absolute',
    top: 16,
    left: 16,
    width: 42,
    height: 42,
    borderTopWidth: 8,
    borderLeftWidth: 8,
    borderColor: '#0E1726',
    borderTopLeftRadius: 16,
  },
  qrCornerTR: {
    display: 'none',
    position: 'absolute',
    top: 16,
    right: 16,
    width: 42,
    height: 42,
    borderTopWidth: 8,
    borderRightWidth: 8,
    borderColor: '#0E1726',
    borderTopRightRadius: 16,
  },
  qrCornerBL: {
    display: 'none',
    position: 'absolute',
    bottom: 16,
    left: 16,
    width: 42,
    height: 42,
    borderBottomWidth: 8,
    borderLeftWidth: 8,
    borderColor: '#0E1726',
    borderBottomLeftRadius: 16,
  },
  qrBrand: {
    display: 'none',
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#0E1726',
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiveAddress: {
    color: WALLET_COLORS.text,
    fontFamily: MONO_FONT,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
  },
  receiveActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 18,
  },
  receiveAction: {
    alignItems: 'center',
    gap: 8,
  },
  receiveActionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiveActionLabel: {
    color: WALLET_COLORS.textMuted,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 12,
  },
});
