module.exports = {
  preset: 'react-native',
  moduleNameMapper: {
    '^@locales$': '<rootDir>/src/locales/index.ts',
    '^@navigation$': '<rootDir>/src/navigation/index.ts',
    '^@assets/(.*)$': '<rootDir>/src/assets/$1',
    '^@app-types/(.*)$': '<rootDir>/src/types/$1',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@locales/(.*)$': '<rootDir>/src/locales/$1',
    '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
    '^@screens/(.*)$': '<rootDir>/src/screens/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@store/(.*)$': '<rootDir>/src/store/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
  },
};
