import { StyleSheet } from 'react-native';

import {
  DISPLAY_FONT,
  MONO_FONT,
  SANS_FONT,
  SANS_FONT_SEMIBOLD,
  WALLET_COLORS,
} from '@components/ui/walletDesign';

export const walletFlowStyles = StyleSheet.create({
  flowScroll: {
    paddingBottom: 24,
    gap: 14,
  },
  sendPickResultsScroll: {
    flex: 1,
    minHeight: 0,
  },
  sendPickResultsPanel: {
    flex: 1,
  },
  sendPickResultsContent: {
    paddingBottom: 24,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  formScroll: {
    paddingVertical: 16,
    gap: 18,
  },
  receiveScroll: {
    paddingVertical: 16,
    gap: 18,
  },
  searchField: {
    marginTop: 12,
    width: '100%',
    minHeight: 56,
    alignSelf: 'stretch',
  },
  manageControls: {
    gap: 12,
    marginTop: 12,
  },
  manageSearchField: {
    width: '100%',
    minHeight: 56,
    alignSelf: 'stretch',
  },
  sendPickFilterScroll: {
    flexGrow: 0,
    flexShrink: 0,
    maxHeight: 66,
  },
  chipRow: {
    gap: 10,
    paddingTop: 12,
    paddingBottom: 10,
    alignItems: 'center',
  },
  chipRowCompact: {
    gap: 10,
    paddingBottom: 6,
    alignItems: 'center',
  },
  filterChip: {
    minWidth: 52,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  filterChipOn: {
    borderColor: WALLET_COLORS.signalBorder,
    backgroundColor: WALLET_COLORS.signalSoft,
  },
  filterChipText: {
    color: WALLET_COLORS.text,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 13,
  },
  filterChipTextOn: {
    color: WALLET_COLORS.text,
  },
  tokenListCard: {
    marginTop: 4,
  },
  tokenRow: {
    minHeight: 76,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  tokenDivider: {
    height: 1,
    backgroundColor: '#203149',
    marginLeft: 66,
    marginRight: 12,
  },
  coin: {
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coinText: {
    color: '#FFFFFF',
    fontFamily: DISPLAY_FONT,
  },
  coinLogo: {
    borderRadius: 999,
  },
  tokenInfo: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    gap: 4,
    alignItems: 'flex-start',
  },
  inlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  tokenMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 6,
  },
  tokenSymbol: {
    color: WALLET_COLORS.text,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 15,
  },
  tokenNetworkTag: {
    color: WALLET_COLORS.textSoft,
    fontFamily: MONO_FONT,
    fontSize: 10,
    borderRadius: 6,
    backgroundColor: WALLET_COLORS.surfaceSoft,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  tokenName: {
    color: WALLET_COLORS.textSoft,
    fontFamily: SANS_FONT,
    fontSize: 12,
    textAlign: 'left',
  },
  tokenRight: {
    width: 132,
    flexShrink: 0,
    marginLeft: 'auto',
    alignItems: 'flex-end',
    gap: 4,
  },
  tokenValue: {
    color: WALLET_COLORS.text,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 14,
    width: '100%',
    textAlign: 'right',
  },
  tokenBalance: {
    color: WALLET_COLORS.textSoft,
    fontFamily: MONO_FONT,
    fontSize: 12,
    width: '100%',
    textAlign: 'right',
  },
  networkHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surface,
  },
  networkHeroText: {
    flex: 1,
  },
  networkHeroTitle: {
    color: WALLET_COLORS.text,
    fontFamily: DISPLAY_FONT,
    fontSize: 20,
  },
  networkHeroSub: {
    color: WALLET_COLORS.textSoft,
    fontFamily: MONO_FONT,
    fontSize: 12,
    marginTop: 4,
  },
  networkBadge: {
    minHeight: 28,
    paddingHorizontal: 10,
    backgroundColor: WALLET_COLORS.surfaceSoft,
  },
  networkBadgeText: {
    color: WALLET_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 10,
  },
  fieldGroup: {
    gap: 8,
  },
  fieldInput: {
    flex: 1,
    color: WALLET_COLORS.text,
    fontFamily: SANS_FONT,
    fontSize: 14,
    padding: 0,
  },
  fieldInputLarge: {
    fontFamily: DISPLAY_FONT,
    fontSize: 24,
    letterSpacing: -0.8,
  },
  fieldActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  fieldActionText: {
    color: WALLET_COLORS.signal,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 13,
  },
  amountTag: {
    minHeight: 30,
    paddingHorizontal: 10,
    backgroundColor: WALLET_COLORS.surfaceSoft,
  },
  amountTagText: {
    color: WALLET_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 11,
  },
  approxText: {
    color: WALLET_COLORS.textSoft,
    fontFamily: SANS_FONT,
    fontSize: 12,
    marginTop: 4,
  },
  errorText: {
    color: WALLET_COLORS.danger,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 12,
  },
  sheetHost: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
  },
  sheetScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(3, 6, 10, 0.82)',
  },
  sheetCard: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: '#11161F',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    gap: 14,
  },
  sheetGrab: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    borderRadius: 999,
    backgroundColor: WALLET_COLORS.borderStrong,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sheetIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetTitle: {
    flex: 1,
    color: WALLET_COLORS.text,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 16,
    textAlign: 'center',
  },
  sheetStep: {
    color: WALLET_COLORS.textLow,
    fontFamily: MONO_FONT,
    fontSize: 11,
  },
  reviewAmountWrap: {
    alignItems: 'center',
    gap: 4,
  },
  reviewAmount: {
    color: WALLET_COLORS.text,
    fontFamily: DISPLAY_FONT,
    fontSize: 34,
    letterSpacing: -1.2,
  },
  reviewAmountUnit: {
    color: WALLET_COLORS.textSoft,
    fontFamily: DISPLAY_FONT,
    fontSize: 18,
  },
  reviewUsd: {
    color: WALLET_COLORS.textSoft,
    fontFamily: MONO_FONT,
    fontSize: 12,
  },
  reviewCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surface,
    overflow: 'hidden',
  },
  reviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: WALLET_COLORS.border,
  },
  reviewRowLast: {
    borderBottomWidth: 0,
  },
  reviewLabel: {
    color: WALLET_COLORS.textLow,
    fontFamily: MONO_FONT,
    fontSize: 10,
    textTransform: 'uppercase',
  },
  reviewValue: {
    flex: 1,
    textAlign: 'right',
    color: WALLET_COLORS.text,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 12,
  },
  sheetActions: {
    gap: 10,
  },
  resultIcon: {
    alignSelf: 'center',
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 2,
    borderColor: WALLET_COLORS.success,
    backgroundColor: WALLET_COLORS.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultTitle: {
    color: WALLET_COLORS.text,
    fontFamily: DISPLAY_FONT,
    fontSize: 24,
    textAlign: 'center',
  },
  resultBody: {
    color: WALLET_COLORS.textSoft,
    fontFamily: SANS_FONT,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  resultCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surface,
    padding: 14,
    gap: 8,
  },
  resultLabel: {
    color: WALLET_COLORS.textLow,
    fontFamily: MONO_FONT,
    fontSize: 10,
    textTransform: 'uppercase',
  },
  resultHash: {
    color: WALLET_COLORS.text,
    fontFamily: MONO_FONT,
    fontSize: 12,
    lineHeight: 18,
  },
  resultMeta: {
    color: WALLET_COLORS.textSoft,
    fontFamily: SANS_FONT,
    fontSize: 11,
  },
  warningCard: {
    padding: 14,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  warningIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: WALLET_COLORS.signalSoft,
  },
  warningIconAmber: {
    backgroundColor: WALLET_COLORS.warningSoft,
  },
  warningText: {
    flex: 1,
    color: WALLET_COLORS.textMuted,
    fontFamily: SANS_FONT,
    fontSize: 12.5,
    lineHeight: 18,
  },
  warningStrong: {
    color: WALLET_COLORS.text,
    fontFamily: SANS_FONT_SEMIBOLD,
  },
  receiveCoinHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  receiveCoinText: {
    color: WALLET_COLORS.text,
    fontFamily: DISPLAY_FONT,
    fontSize: 24,
  },
  receiveBadge: {
    minHeight: 28,
    paddingHorizontal: 10,
    backgroundColor: WALLET_COLORS.surfaceSoft,
  },
  receiveBadgeText: {
    color: WALLET_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 11,
  },
  qrCard: {
    padding: 18,
    alignItems: 'center',
    gap: 16,
  },
  qrMock: {
    width: 238,
    height: 238,
    borderRadius: 22,
    backgroundColor: '#F2F5FA',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  qrCornerTL: {
    position: 'absolute',
    top: 16,
    left: 16,
    width: 42,
    height: 42,
    borderTopWidth: 8,
    borderLeftWidth: 8,
    borderColor: '#0E1726',
    borderTopLeftRadius: 16,
  },
  qrCornerTR: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 42,
    height: 42,
    borderTopWidth: 8,
    borderRightWidth: 8,
    borderColor: '#0E1726',
    borderTopRightRadius: 16,
  },
  qrCornerBL: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    width: 42,
    height: 42,
    borderBottomWidth: 8,
    borderLeftWidth: 8,
    borderColor: '#0E1726',
    borderBottomLeftRadius: 16,
  },
  qrBrand: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#0E1726',
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiveAddress: {
    color: WALLET_COLORS.text,
    fontFamily: MONO_FONT,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
  },
  receiveActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 18,
  },
  receiveAction: {
    alignItems: 'center',
    gap: 8,
  },
  receiveActionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiveActionLabel: {
    color: WALLET_COLORS.textMuted,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 12,
  },
  touchBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 32,
  },
  scanFlag: {
    minHeight: 30,
    paddingHorizontal: 12,
    gap: 8,
    backgroundColor: WALLET_COLORS.signalSoft,
    borderColor: WALLET_COLORS.signalBorder,
  },
  scanFlagDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: WALLET_COLORS.signal,
  },
  scanFlagText: {
    color: '#8CD0FF',
    fontFamily: MONO_FONT,
    fontSize: 10,
    textTransform: 'uppercase',
  },
  touchStage: {
    width: 260,
    height: 260,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
    marginBottom: 26,
  },
  touchRingOne: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 1,
    borderColor: 'rgba(79, 180, 255, 0.12)',
  },
  touchRingTwo: {
    position: 'absolute',
    width: 170,
    height: 170,
    borderRadius: 85,
    borderWidth: 1,
    borderColor: 'rgba(79, 180, 255, 0.2)',
  },
  touchRingThree: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: 'rgba(79, 180, 255, 0.32)',
  },
  touchCore: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 1,
    borderColor: WALLET_COLORS.signalBorder,
    backgroundColor: WALLET_COLORS.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  touchTitle: {
    color: WALLET_COLORS.text,
    fontFamily: DISPLAY_FONT,
    fontSize: 26,
    lineHeight: 30,
    textAlign: 'center',
    letterSpacing: -0.8,
  },
  touchBodyText: {
    color: WALLET_COLORS.textMuted,
    fontFamily: SANS_FONT,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 12,
    paddingHorizontal: 18,
  },
  manageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  manageChainPill: {
    minHeight: 22,
    paddingHorizontal: 8,
    backgroundColor: WALLET_COLORS.surfaceSoft,
  },
  manageChainText: {
    color: WALLET_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 10,
  },
  tabSwitch: {
    flexDirection: 'row',
    marginTop: 12,
    borderBottomWidth: 1,
    borderBottomColor: WALLET_COLORS.border,
  },
  tabSwitchItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 14,
    gap: 8,
  },
  tabSwitchText: {
    color: WALLET_COLORS.textSoft,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 15,
  },
  tabSwitchTextOn: {
    color: WALLET_COLORS.text,
  },
  tabSwitchIndicator: {
    height: 3,
    width: 80,
    borderRadius: 999,
    backgroundColor: WALLET_COLORS.signal,
  },
  networkPillText: {
    flex: 1,
    color: WALLET_COLORS.text,
    fontFamily: SANS_FONT_SEMIBOLD,
    fontSize: 15,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: WALLET_COLORS.border,
    backgroundColor: WALLET_COLORS.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
});


export default walletFlowStyles;
