import { StyleSheet } from 'react-native';

import {
  DISPLAY_FONT,
  DISPLAY_FONT_MEDIUM,
  MONO_FONT,
  type WalletColors,
} from '@components/ui/walletDesign';

export const createSettingsStyles = (colors: WalletColors) =>
  StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    safeArea: {
      flex: 1,
    },
    topBar: {
      paddingTop: 6,
      paddingHorizontal: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    backButton: {
      width: 32,
      height: 32,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    backButtonGhost: {
      width: 32,
      height: 32,
    },
    topTitle: {
      flex: 1,
      textAlign: 'center',
      fontFamily: DISPLAY_FONT_MEDIUM,
      fontSize: 16,
      color: colors.text,
      letterSpacing: -0.4,
    },
    scrollContent: {
      paddingTop: 14,
      paddingHorizontal: 14,
      paddingBottom: 50,
    },
    profileCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: 'rgba(40, 151, 255, 0.3)',
      backgroundColor: colors.surfaceAlt,
      marginBottom: 18,
    },
    profileAvatar: {
      width: 44,
      height: 44,
      borderRadius: 14,
      overflow: 'hidden',
    },
    profileAvatarGradient: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: '#2577D8',
    },
    profileAvatarCore: {
      position: 'absolute',
      top: 6,
      left: 6,
      right: 6,
      bottom: 6,
      borderRadius: 10,
      backgroundColor: '#0D1A2E',
    },
    profileText: {
      flex: 1,
    },
    profileName: {
      color: colors.text,
      fontFamily: DISPLAY_FONT,
      fontSize: 15,
      letterSpacing: -0.2,
    },
    profileAddress: {
      marginTop: 2,
      color: colors.textMuted,
      fontFamily: MONO_FONT,
      fontSize: 11,
      letterSpacing: 0.4,
    },
    profileStatus: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(16, 185, 129, 0.3)',
      backgroundColor: 'rgba(16, 185, 129, 0.12)',
    },
    profileStatusDot: {
      width: 5,
      height: 5,
      borderRadius: 2.5,
      backgroundColor: colors.success,
    },
    profileStatusText: {
      color: '#8DE9C5',
      fontFamily: MONO_FONT,
      fontSize: 10,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    groupWrap: {
      marginBottom: 18,
    },
    groupLabel: {
      paddingHorizontal: 4,
      paddingBottom: 8,
      color: colors.textSoft,
      fontFamily: MONO_FONT,
      fontSize: 10,
      letterSpacing: 1.6,
      textTransform: 'uppercase',
    },
    groupCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    row: {
      minHeight: 76,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    rowPressed: {
      backgroundColor: colors.surfaceAlt,
    },
    rowIcon: {
      width: 32,
      height: 32,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: 'rgba(40, 151, 255, 0.25)',
      backgroundColor: 'rgba(40, 151, 255, 0.12)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    rowIconSoftDanger: {
      borderColor: 'rgba(255, 180, 120, 0.38)',
      backgroundColor: 'rgba(255, 180, 120, 0.12)',
    },
    rowIconHardDanger: {
      borderColor: 'rgba(239, 68, 68, 0.3)',
      backgroundColor: 'rgba(239, 68, 68, 0.14)',
    },
    rowIconX: {
      borderColor: 'rgba(255, 255, 255, 0.16)',
      backgroundColor: 'rgba(255, 255, 255, 0.06)',
    },
    rowIconFacebook: {
      borderColor: 'rgba(24, 119, 242, 0.32)',
      backgroundColor: 'rgba(24, 119, 242, 0.14)',
    },
    rowIconYoutube: {
      borderColor: 'rgba(239, 68, 68, 0.32)',
      backgroundColor: 'rgba(239, 68, 68, 0.14)',
    },
    rowTextCol: {
      flex: 1,
      minWidth: 0,
    },
    rowTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
      letterSpacing: -0.1,
    },
    rowTitleDanger: {
      color: '#FF8A8A',
    },
    rowSubtitle: {
      marginTop: 2,
      color: colors.textSoft,
      fontSize: 11,
      letterSpacing: -0.05,
    },
    rowSeparator: {
      position: 'absolute',
      left: 54,
      right: 14,
      bottom: 0,
      height: 1,
      backgroundColor: colors.border,
    },
    toggle: {
      width: 40,
      height: 22,
      borderRadius: 11,
      backgroundColor: '#223044',
      justifyContent: 'center',
      paddingHorizontal: 2,
    },
    toggleOn: {
      backgroundColor: colors.signal,
    },
    toggleKnob: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: '#FFFFFF',
    },
    toggleKnobOn: {
      alignSelf: 'flex-end',
    },
    metaWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
    },
    metaText: {
      color: colors.textMuted,
      fontFamily: MONO_FONT,
      fontSize: 11,
      letterSpacing: 0.4,
    },
    socialCta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 9,
      paddingVertical: 5,
      borderRadius: 7,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: 'rgba(255, 255, 255, 0.04)',
    },
    socialCtaText: {
      color: colors.textMuted,
      fontFamily: MONO_FONT,
      fontSize: 10,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    versionText: {
      marginTop: 2,
      paddingTop: 2,
      textAlign: 'center',
      color: colors.textSoft,
      fontSize: 11,
      lineHeight: 18,
    },
    versionSub: {
      color: colors.textMuted,
      fontFamily: MONO_FONT,
      fontSize: 10,
      letterSpacing: 0.6,
    },
  });
