import { StyleSheet } from 'react-native';

import {
  PIN_DISPLAY_FONT_BOLD,
  PIN_DISPLAY_FONT_MEDIUM,
  PIN_MONO_FONT,
  PIN_SANS_FONT,
  PIN_SANS_FONT_SEMIBOLD,
} from '@components/ui/pinTheme';

export const COLORS = {
  overlay: 'rgba(3, 5, 9, 0.78)',
  dialog: '#11161F',
  surface: '#171C27',
  surfaceAlt: '#1E2431',
  border: '#272E3E',
  borderStrong: '#384053',
  text: '#E8ECF3',
  textSecondary: '#B6BDCC',
  textMuted: '#7A829A',
  textLow: '#525B73',
  signal: '#0A7CF2',
  signalBright: '#2897FF',
  success: '#10B981',
};

export const styles = StyleSheet.create({
  screenRoot: {
    flex: 1,
    backgroundColor: '#08111B',
  },
  backdrop: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  dialog: {
    width: '100%',
    maxWidth: 390,
  },
  screenDialog: {
    flex: 1,
    width: '100%',
    maxWidth: undefined,
    borderRadius: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  authShell: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.dialog,
    paddingTop: 8,
    paddingBottom: 0,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.58,
    shadowRadius: 36,
    elevation: 26,
  },
  scanShell: {
    minHeight: '96%',
    maxHeight: '96%',
    borderRadius: 34,
    backgroundColor: '#08111B',
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.62,
    shadowRadius: 40,
    elevation: 30,
  },
  grab: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.borderStrong,
    alignSelf: 'center',
    marginBottom: 0,
  },
  headerRow: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerTitle: {
    flex: 1,
    color: COLORS.text,
    fontSize: 17,
    lineHeight: 21,
    fontFamily: PIN_DISPLAY_FONT_MEDIUM,
    letterSpacing: -0.2,
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.surfaceAlt,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabContainer: {
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 18,
    flexDirection: 'row',
    position: 'relative',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceAlt,
    padding: 4,
    minHeight: 44,
  },
  tabIndicator: {
    position: 'absolute',
    left: 4,
    top: 4,
    bottom: 4,
    borderRadius: 999,
    backgroundColor: COLORS.dialog,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
  },
  tabButton: {
    flex: 1,
    zIndex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: -0.1,
  },
  tabLabelActive: {
    color: COLORS.text,
  },
  tabLabelInactive: {
    color: COLORS.textMuted,
  },
  pinContentWrap: {
    paddingHorizontal: 20,
    paddingBottom: 22,
  },
  pinInputCard: {
    paddingTop: 2,
  },
  scanLayout: {
    flex: 1,
  },
  scanHeaderRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
  },
  scanBackButton: {
    width: 40,
    height: 40,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  scanHeaderTitle: {
    flex: 1,
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 28,
    fontFamily: PIN_DISPLAY_FONT_BOLD,
    letterSpacing: -0.8,
  },
  scanHeaderSpacer: {
    width: 40,
    height: 40,
  },
  scanBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 26,
  },
  scanStatePill: {
    minHeight: 30,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(40, 151, 255, 0.3)',
    backgroundColor: 'rgba(40, 151, 255, 0.08)',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scanStateDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.signal,
  },
  scanStateText: {
    color: '#8CD0FF',
    fontSize: 10,
    fontFamily: PIN_MONO_FONT,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
  },
  touchStage: {
    width: 286,
    height: 286,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 34,
    marginBottom: 34,
  },
  touchPulse: {
    position: 'absolute',
    width: 188,
    height: 188,
    borderRadius: 94,
    backgroundColor: 'rgba(15, 52, 101, 0.14)',
  },
  touchRingOne: {
    position: 'absolute',
    width: 274,
    height: 274,
    borderRadius: 137,
    borderWidth: 1,
    borderColor: 'rgba(40, 151, 255, 0.08)',
  },
  touchRingTwo: {
    position: 'absolute',
    width: 198,
    height: 198,
    borderRadius: 99,
    borderWidth: 1,
    borderColor: 'rgba(40, 151, 255, 0.18)',
  },
  touchRingThree: {
    position: 'absolute',
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: 'rgba(40, 151, 255, 0.92)',
    shadowColor: COLORS.signalBright,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 20,
  },
  touchCore: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: 'rgba(18, 24, 37, 0.96)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.signal,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
  },
  touchTitle: {
    color: '#FFFFFF',
    fontSize: 26,
    lineHeight: 34,
    fontFamily: PIN_DISPLAY_FONT_BOLD,
    textAlign: 'center',
    letterSpacing: -0.86,
    paddingHorizontal: 18,
  },
  touchBodyText: {
    color: '#757B93',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: PIN_SANS_FONT,
    textAlign: 'center',
    marginTop: 12,
    paddingHorizontal: 28,
  },
  scanFooter: {
    gap: 10,
  },
  scanPrimaryButton: {
    minHeight: 62,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#2B98FF',
    backgroundColor: '#0A7CF2',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    shadowColor: '#2897FF',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 26,
    elevation: 6,
  },
  scanPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    lineHeight: 22,
    fontFamily: PIN_SANS_FONT_SEMIBOLD,
    letterSpacing: -0.3,
  },
  scanSecondaryButton: {
    minHeight: 62,
    borderRadius: 26,
    backgroundColor: '#151B27',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  scanSecondaryButtonText: {
    color: '#F3F6FB',
    fontSize: 17,
    lineHeight: 22,
    fontFamily: PIN_SANS_FONT_SEMIBOLD,
    letterSpacing: -0.24,
  },
  scanGhostButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanGhostButtonText: {
    color: '#B0B8C9',
    fontSize: 16,
    lineHeight: 20,
    fontFamily: PIN_SANS_FONT_SEMIBOLD,
    letterSpacing: -0.2,
  },
  statusSection: {
    paddingHorizontal: 20,
  },
  flagWrap: {
    alignSelf: 'flex-start',
    marginBottom: 12,
    marginTop: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(40, 151, 255, 0.24)',
    backgroundColor: 'rgba(40, 151, 255, 0.08)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  flagDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: COLORS.signalBright,
  },
  flagText: {
    color: COLORS.signalBright,
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  pinPromptHeader: {
    marginBottom: 12,
  },
  statusText: {
    color: COLORS.textSecondary,
    fontSize: 13.5,
    lineHeight: 20,
    letterSpacing: -0.08,
    marginBottom: 14,
  },
  logBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: 'rgba(10, 14, 23, 0.72)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.signalBright,
  },
  logText: {
    flex: 1,
    color: COLORS.textSecondary,
    fontSize: 10.5,
    lineHeight: 16,
    letterSpacing: -0.08,
  },
  visualContainer: {
    minHeight: 188,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    marginTop: 6,
  },
  pulseRing: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(40, 151, 255, 0.22)',
  },
  viewfinder: {
    position: 'relative',
    width: 148,
    height: 148,
    borderRadius: 74,
    borderWidth: 3,
    borderColor: COLORS.signalBright,
    backgroundColor: '#060A12',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: COLORS.signalBright,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 30,
    elevation: 6,
  },
  viewfinderGlow: {
    position: 'absolute',
    width: 144,
    height: 144,
    borderRadius: 72,
    backgroundColor: 'rgba(40, 151, 255, 0.06)',
  },
  viewfinderInner: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    bottom: 10,
    borderRadius: 64,
    backgroundColor: 'rgba(17, 30, 49, 0.34)',
  },
  scanCorner: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderColor: COLORS.signalBright,
    borderWidth: 2,
  },
  scanCornerTopLeft: {
    top: -6,
    left: -6,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderTopLeftRadius: 6,
  },
  scanCornerTopRight: {
    top: -6,
    right: -6,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    borderTopRightRadius: 6,
  },
  scanCornerBottomLeft: {
    bottom: -6,
    left: -6,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderBottomLeftRadius: 6,
  },
  scanCornerBottomRight: {
    bottom: -6,
    right: -6,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderBottomRightRadius: 6,
  },
  scanBeam: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: COLORS.signalBright,
    shadowColor: COLORS.signalBright,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
  },
  cardIcon: {
    width: 70,
    height: 44,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: '#14202F',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  cardChip: {
    position: 'absolute',
    top: 6,
    left: 6,
    width: 14,
    height: 10,
    borderRadius: 2,
    backgroundColor: '#D8A852',
  },
  cardLines: {
    position: 'absolute',
    right: 6,
    bottom: 5,
    alignItems: 'flex-end',
  },
  cardLine: {
    width: 18,
    height: 2,
    borderRadius: 1,
    backgroundColor: COLORS.signalBright,
    opacity: 0.7,
  },
  cardLineSecond: {
    marginTop: 4,
  },
  cardLineThird: {
    marginTop: 4,
    width: 14,
  },
  scanTip: {
    position: 'absolute',
    bottom: 10,
    left: 24,
    right: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: COLORS.surfaceAlt,
    paddingHorizontal: 12,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  scanTipAccent: {
    color: COLORS.signalBright,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  scanTipDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: COLORS.textMuted,
  },
  scanTipText: {
    color: COLORS.textMuted,
    fontSize: 9,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  successCore: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 2,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.success,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 22,
  },
  actions: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 22,
    gap: 8,
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.signalBright,
    backgroundColor: COLORS.signal,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: COLORS.signalBright,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 4,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  ghostButton: {
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostButtonText: {
    color: COLORS.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
});
